[workspace]

members = [
    "hotpatch",
    "hotpatch_macros",
    "examples/hello_world/hw_bin",
    "examples/hello_world/hw_obj",
    "examples/threads/threads_bin",
    "examples/threads/threads_obj",
    "examples/classes/classes_bin",
    "examples/classes/classes_obj",
]