[package]
name = "hotpatch"
version = "0.1.0"
authors = ["Shizcow <pohl.devin@gmail.com>"]
edition = "2018"

[dependencies]
libloading = "0.6"
lazy_static = "1.4.0"
simple-error = "0.2.2"
hotpatch_macros = {path = "../hotpatch_macros"}
