[package]
name = "src_bin"
version = "0.1.0"
authors = ["Shizcow <pohl.devin@gmail.com>"]
edition = "2018"

[dependencies]
lazy_static = "1.4.0"
patchable = {path = "../patchable"}
patch_proc = {path = "../patch_proc"}