[package]
name = "threads_obj"
version = "0.1.0"
authors = ["Shizcow <pohl.devin@gmail.com>"]
edition = "2018"

[lib]
name = "threads_obj"
crate-type = ["dylib"]

[dependencies]
hotpatch = {path = "../../../hotpatch"}
