[package]
name = "multiple_obj2"
version = "0.1.0"
authors = ["Shizcow <pohl.devin@gmail.com>"]
edition = "2018"

[lib]
name = "multiple_obj2"
crate-type = ["cdylib"]

[dependencies]
hotpatch = {path = "../../../hotpatch"}
